config/routes.rb
Rails.application.routes.draw do

  resources :wines
  resources :wineries
  root 'wineries#index'

end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :winery
  validates :name, :vintage, :description, :winery, presence: true
end

app/models/winery.rb
class Winery < ActiveRecord::Base
  has_many :wines
  validates :name, :location, :rating, presence: true
  # validates :rating, numericality: { less_than: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
  before_action :set_winery, only: [:show, :edit, :update, :destroy]

  # GET /wineries
  # GET /wineries.json
  def index
    @wineries = Winery.all
  end

  # GET /wineries/1
  # GET /wineries/1.json
  def show
  end

  # GET /wineries/new
  def new
    @winery = Winery.new
  end

  # GET /wineries/1/edit
  def edit
  end

  # POST /wineries
  # POST /wineries.json
  def create
    @winery = Winery.new(winery_params)

    respond_to do |format|
      if @winery.save
        format.html { redirect_to @winery, notice: 'Winery was successfully created.' }
        format.json { render :show, status: :created, location: @winery }
      else
        format.html { render :new }
        format.json { render json: @winery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wineries/1
  # PATCH/PUT /wineries/1.json
  def update
    respond_to do |format|
      if @winery.update(winery_params)
        format.html { redirect_to @winery, notice: 'Winery was successfully updated.' }
        format.json { render :show, status: :ok, location: @winery }
      else
        format.html { render :edit }
        format.json { render json: @winery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wineries/1
  # DELETE /wineries/1.json
  def destroy
    @winery.destroy
    respond_to do |format|
      format.html { redirect_to wineries_url, notice: 'Winery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_winery
      @winery = Winery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def winery_params
      params.require(:winery).permit(:name, :location, :rating)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_params
      params.require(:wine).permit(:name, :vintage, :description, :winery_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WinoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wineries/_form.html.erb
<%= form_for(@winery) do |f| %>
  <% if @winery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@winery.errors.count, "error") %> prohibited this winery from being saved:</h2>

      <ul>
      <% @winery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wineries/edit.html.erb
<h1>Editing Winery</h1>

<%= render 'form' %>

<%= link_to 'Show', @winery %> |
<%= link_to 'Back', wineries_path %>

app/views/wineries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wineries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wineries.each do |winery| %>
      <tr>
        <td><%= winery.name %></td>
        <td><%= winery.location %></td>
        <td><%= winery.rating %></td>
        <td><%= link_to 'Show', winery %></td>
        <td><%= link_to 'Edit', edit_winery_path(winery) %></td>
        <td><%= link_to 'Destroy', winery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Winery', new_winery_path %>

app/views/wineries/new.html.erb
<h1>New Winery</h1>

<%= render 'form' %>

<%= link_to 'Back', wineries_path %>

app/views/wineries/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @winery.name %> </h2>

<p>
  <strong>Location:</strong>
  <%= @winery.location %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @winery.rating %>
</p>

<p>
  <strong>Wines:</strong>
  <ul id="wine_list">
    <% @winery.wines.each do |wine| %>
    <li>
      <a href="/wines/<%= wine.id %>">
        <%= wine.name %>
      </a>
    </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_winery_path(@winery) %> |
<%= link_to 'Back', wineries_path %>

<p>
  Wine Name: <br>
  <input type="text" name="name" id="add_wine_field" /> <br>
  Vintage: <br>
  <input type="integer" name="vintage" id="add_vintage_field" /> <br>
  Description: <br>
  <input type="text" name="description" id="add_description_field" /> <br>
  <input type="hidden" name="winery_id" id="add_winery_id" value="<%= @winery.id %>" /> <br>
  <input type="button" id="add_wine_button" value="Add Wine" />
</p>

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :vintage %><br>
    <%= f.number_field :vintage %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :winery_id %><br>
    <%= f.text_field :winery_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vintage</th>
      <th>Description</th>
      <th>Winery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.vintage %></td>
        <td><%= wine.description %></td>
        <td><%= wine.winery.name %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @wine.name %> </h2>


<p>
  <strong>Vintage:</strong>
  <%= @wine.vintage %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wine.description %>
</p>

<p>
  <strong>Winery:</strong>
  <a href="/wineries/<%= @wine.winery.id %>">
    <%= @wine.winery.name %>
  </a>
</p>


<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>